# Generated by Django 2.2.5 on 2019-11-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('Disease_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Disease_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Disease_definition', models.TextField(blank=True, max_length=200, null=True)),
                ('Alias', models.CharField(blank=True, max_length=200, null=True)),
                ('MeSH_id', models.CharField(blank=True, max_length=200, null=True)),
                ('OMIM_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Orphanet_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ICD10CM_id', models.CharField(blank=True, max_length=200, null=True)),
                ('UMLS_id', models.CharField(blank=True, max_length=200, null=True)),
                ('MedDRA_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-Disease_id',),
            },
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('Herb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Chinese_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Pinyin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Latin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('English_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Properties', models.CharField(blank=True, max_length=200, null=True)),
                ('Meridians', models.CharField(blank=True, max_length=200, null=True)),
                ('Function', models.TextField(blank=True, null=True)),
                ('Class_Chinese', models.CharField(blank=True, max_length=200, null=True)),
                ('Class_English', models.CharField(blank=True, max_length=200, null=True)),
                ('UsePart', models.CharField(blank=True, max_length=200, null=True)),
                ('TCMID_id', models.CharField(blank=True, max_length=200, null=True)),
                ('TCM_ID_id', models.CharField(blank=True, max_length=200, null=True)),
                ('TCMSP_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-Herb_id',),
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('Target_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Gene_symbol', models.CharField(blank=True, max_length=200, null=True)),
                ('Chromosome', models.CharField(blank=True, max_length=200, null=True)),
                ('Gene_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Protein_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Alias', models.TextField(blank=True, null=True)),
                ('HIT_id', models.CharField(blank=True, max_length=200, null=True)),
                ('TCMSP_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Ensembl_id', models.CharField(blank=True, max_length=200, null=True)),
                ('NCBI_id', models.CharField(blank=True, max_length=200, null=True)),
                ('HGNC_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Vega_id', models.CharField(blank=True, max_length=200, null=True)),
                ('GenBank_Gene_id', models.CharField(blank=True, max_length=200, null=True)),
                ('GenBank_Protein_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Uniprot_id', models.CharField(blank=True, max_length=200, null=True)),
                ('PDB_id', models.CharField(blank=True, max_length=200, null=True)),
                ('OMIM_id', models.CharField(blank=True, max_length=200, null=True)),
                ('miRBase_id', models.CharField(blank=True, max_length=200, null=True)),
                ('IMGT_GENE_DB_id', models.CharField(blank=True, max_length=200, null=True)),
                ('diseases', models.ManyToManyField(to='rambler.Disease')),
            ],
            options={
                'ordering': ('-Target_id',),
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('Prescription_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Pinyin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Chinese_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Composition', models.CharField(blank=True, max_length=200, null=True)),
                ('Pinyin_composition', models.CharField(blank=True, max_length=200, null=True)),
                ('Indication', models.CharField(blank=True, max_length=200, null=True)),
                ('Use_method', models.TextField(blank=True, null=True)),
                ('References', models.TextField(blank=True, null=True)),
                ('herbs', models.ManyToManyField(to='rambler.Herb')),
            ],
            options={
                'ordering': ('-Prescription_id',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('Ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Molecule_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Molecule_formula', models.CharField(blank=True, max_length=200, null=True)),
                ('Molecule_weight', models.CharField(blank=True, max_length=200, null=True)),
                ('OB_score', models.CharField(blank=True, max_length=200, null=True)),
                ('Alias', models.TextField(blank=True, null=True)),
                ('PubChem_id', models.CharField(blank=True, max_length=200, null=True)),
                ('CAS_id', models.CharField(blank=True, max_length=200, null=True)),
                ('TCMID_id', models.CharField(blank=True, max_length=200, null=True)),
                ('TCM_ID_id', models.CharField(blank=True, max_length=200, null=True)),
                ('TCMSP_id', models.CharField(blank=True, max_length=200, null=True)),
                ('targets', models.ManyToManyField(to='rambler.Target')),
            ],
            options={
                'ordering': ('-Ingredient_id',),
            },
        ),
        migrations.AddField(
            model_name='herb',
            name='ingredients',
            field=models.ManyToManyField(to='rambler.Ingredient'),
        ),
    ]
